### ISSUE TITLE
Missing glottocode (maybe?): nuuc1236

### ISSUE THREAD

**Issue by SamPassmore** [glottolog/pyglottolog#25]
Hi, 

I have been using pyglottolog but one of my glottocodes ("nuuc1236") doesn't appear to be a languoid, despite existing on glottolog.com
https://glottolog.org/resource/languoid/id/nuuc1236 

The code previously worked with this glottocode so I am unsure what has changed. 
Do you have any ideas? 

```
>>> glottolog = {l.id: l for l in Glottolog(gdir).languoids()}
>>> print(glottolog.get("nuuc1236"))
None
```

**Comment by xrotwang** [comment]
Hm. Cannot confirm with current HEAD:
```
$ glottolog tree nuuc1236
INFO    glottolog/glottolog at /home/forkel/venvs/glottolog/glottolog
Wakashan [waka1280]
   └─ Southern Wakashan [sout2981]
      └─ Nuu-chah-nulth [nuuc1236]
```
and 
```python
>>> from pyglottolog import Glottolog
>>> Glottolog('.').languoid('nuuc1236').name
'Nuu-chah-nulth'
```

Maybe you are passing the wrong `gdir`? Older versions of `pyglottolog` didn't have any error reporting for this case - so a missing `languoids` directory might result in the behaviour you see? Or do other Glottocodes resolve ok?

**Comment by SamPassmore** [comment]
If I output the languoids using:

`glottolog languioids --output [output file]`

nuuc1236 is not in there. 
Other Glottocodes resolve ok though (I tried stan1293 & nucl1643).

Have uninstalled and re-installed pyglottolog via pip and still get the same thing. Using python 3.8.1 and pyglottolog-3.0.0 if that matters. 

FWIW I can resolve higher up this language tree in Makah (maka1318) but not the sister languiod Nootkan (noot1238) or any of the the daughter languoids (nuuc1236 & diti1235).

**Comment by xrotwang** [comment]
What does `git status` result in for the Glottolog directory?

SamPassmore <notifications@github.com> schrieb am Mi., 25. März 2020, 21:55:

**Comment by SamPassmore** [comment]
There seems to be lots of modified, deleted, and untracked files. 
cldfbench is being used to deal with this aspect though - so I ran catconfig & catupdate

But this didn't fix it. 

So I just deleted the glottolog repo and redownloaded it and it seems to work now. Not sure how it got so out of sync though. 

Thanks for your help!
