### ISSUE TITLE
Quick lookup of valid glottolog code

### ISSUE THREAD

**Issue by SimonGreenhill** [glottolog/pyglottolog#28]
I feel like lots of the glottolog look ups we do are just "does this glottocode exist" (followed by "does this glottocode exist and is not in bookkeeping". There must be a better way to do this rather than iterating over the full tree. 

Does `glottolog/languoids/glottocodes.json` contain enough info to make a quick lookup table in a method like `is_glottocode` which simply returns `True` or `False`? Possibly coupled with looking at 'superseded.csv'?

**Comment by xrotwang** [comment]
`glottocodes.json` is just a bit better than a regex check, but cannot guarantee validity (only detect some invalidity). `superseded.csv` is only created for each release, not for each commit.

That said, I guess traversing the whole tree, but **not** reading any files should be considerably faster - and provide all we need here via directory names.

**Comment by SimonGreenhill** [comment]
that could work, or if you don't mind having generated files in the repos, you could have a `glottocode-<version>.json` of valid codes?

(None of this is urgent BTW)

**Comment by xrotwang** [comment]
I do mind :) - or at least try to keep generated content to a minimum.

**Comment by xrotwang** [comment]
Hm, just using `os.walk` still takes a couple of seconds - about half as long as `Glottolog.languoids`.

**Comment by SimonGreenhill** [comment]
ok, so that's not really worth it then :/ have you tried `os.scandir`? ( I can't remember if this is now how `os.walk` works anyway)

**Comment by xrotwang** [comment]
It is.

**Comment by SimonGreenhill** [comment]
ahh yep, [from 3.5](https://docs.python.org/3/library/os.html#os.walk)

**Comment by SimonGreenhill** [comment]
ok, close as cantfix?
