### ISSUE TITLE
Issue on Dendrograms

### ISSUE THREAD

**Issue by kak-to-tak** [glottolog/pyglottolog#35]
First of all, thank you for this amazing package!
Is there an easy way to plot a dendrogram of arbitrary chosen languages. Suppose, I have a list of random languoids, is it possible to get a phylogenic hierarchy of the sample or should it be somehow iteratively reconstructed top to bottom?

**Comment by xrotwang** [comment]
Glottolog does only have per-family trees, no global one. But if you are interested in "arbitrary chosen languages" from the same family, you can use `pyglottolog` together with the [newick](https://pypi.org/project/newick/) as follows:
```python
from pyglottolog import Glottolog
import newick

api = Glottolog('PATH/TO/CLONE/OF/glottolog/glottolog')
indo1319 = api.languoid('indo1319')
tree = indo1319.newick_node(template='{l.id}', maxlevel=api.languoid_levels.language)
tree.prune_by_names(['myce1241', 'olde1238', 'stan1295'], inverse=True)
tree.remove_redundant_nodes()
print(tree.ascii_art())
```
to get something like this:
```
                      ┌─stan1295
           ┌─west2793─┤
──indo1319─┤          └─olde1238
           └─myce1241
```

**Comment by kak-to-tak** [comment]
@xrotwang Thank you for a quick reply! I tried it out and it works nice, however, it's hard to interpret the results with the nodes named as ids. Is there a way to display the tree with languoid names?

**Comment by xrotwang** [comment]
```python
api = Glottolog('.')

indo1319 = api.languoid('indo1319')
tree = indo1319.newick_node(template='{l.id}', maxlevel=api.languoid_levels.language)
tree.prune_by_names(['myce1241', 'olde1238', 'stan1295'], inverse=True)
for node in tree.walk():
    if node.name:
        node.name = api.languoid(node.name).name
tree.remove_redundant_nodes()
print(tree.ascii_art())
```
gives
```
 
                                                          ┌─German
                             ┌─West Germanic──────────────┤
──Indo-European──────────────┤                            └─Old English (ca. 450-1100)
                             └─Mycenaean Greek

```

**Comment by kak-to-tak** [comment]
Thank you so much!

**Comment by xrotwang** [comment]
More ways to do this are described at https://github.com/glottolog/cookbook/blob/master/treemaker/README.md
