### ISSUE TITLE
lff2tree does not update ISO codes, when NOCODE_* switches to three-letter ISO code.

### ISSUE THREAD

**Issue by xrotwang** [glottolog/pyglottolog#47]
There seems to be a glitch in that when languages which did not have an iso-code get one, it's not updated as intended. `lff2tree` did update an older `NOCODE_ Southern-Pinghua` to `csp` in the 'hid' field in the .md but did not put csp in the iso-639-3 field. I haven't checked the corresponding pyglottolog code but I suggest the following course of action:
- lff2tree updates hid unconditionally as well as iso-639-3 if the code in question is a legal iso-639-3 at the time lff2tree is run
- Before a Glottolog release, some script checks which hid:s are also valid iso-639-3 at the time just before the release and updates if so
This is because I might update the field in lff.txt when an iso-639-3 is pre-determined but not yet in the list of legal iso-639-3:s. (Alternatively one could just take any three-letter hid to count as becoming an iso-639-3 some day but this will incur OLAC and other errors)

**Comment by xrotwang** [comment]
Maybe we should also add a check along the lines of
```python
from pyglottolog import Glottolog
api = Glottolog()
import re
iso = re.compile('[a-z]{3}')
for l in api.languoids():
    if iso.fullmatch(l.hid or '') and not l.iso and l.hid in api.iso:
        raise ValueError('{} [{}]: ISO-like hid "{}" but no ISO code'.format(l.name, l.id, l.hid))
```

**Comment by xrotwang** [comment]
@d97hah It looks like the code is already doing the right thing, see https://github.com/glottolog/pyglottolog/blob/7361560d1dfb638ffe4db4cb5e5449e44cebe630/src/pyglottolog/lff.py#L67-L68

When it reads something like
```
Language [abcd1234] abc
```
where `abcd1234` had `hid=NOCODE_*` before, it will not only reset `hid`, but also `iso`.

**But** this only happens when the ISO code is valid; and what's valid is decided based on the copy of the ISO code tables available in `REPOS/build`. Here's how this looks like for me:
```
glottolog/glottolog$ la build/iso-*
build/iso-639-3_Code_Tables_20180123.zip
build/iso-639-3_Code_Tables_20190125.zip
build/iso-639-3_Code_Tables_20190408.zip
build/iso-639-3_Code_Tables_20200130.zip
build/iso-639-3_Code_Tables_20200515.zip
```

Maybe you are missing the latest tables, i.e. https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Code_Tables_20200515.zip ?

**Comment by xrotwang** [comment]
So maybe, we'd need a `glottolog info` command, listing the current environment, i.e. ISO tables version, etc. Automatically downloading the tables might be possible, but turned out to be fragile in the past.

**Comment by d97hah** [comment]
Yes it's doing the right thing already, the only thing I had in mind was
the case when I insert a code which is not yet a iso-639-3 even in the
newest table at the time I run lff2tree with that update. Now that I think
of it, all that is needed is that I make sure I have an updated iso-table
at some point close to a release date. I can see to that and no other
amendments are needed IMHO.

Pada tanggal Jum, 15 Jan 2021 pukul 09.32 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
They seem to have an almost regular end-of-january release at SIL, so it's probably worth checking again soon.
