### ISSUE TITLE
Tutorials and guidance for more programmatic access examples

### ISSUE THREAD

**Issue by chrzyki** [glottolog/pyglottolog#5]
We now have multiple ways of accessing the `Glottolog()` API, e.g. from a working Lexibank configuration as proposed by @LinguList:

```python
from pylexibank.__main__ import configure
conf = configure()
conf.glottolog.languoid('stand1295')
```

'Working' here means a `config.ini` in `~/.config/pylexibank/` with paths to clones of https://github.com/clld/glottolog and https://github.com/concepticon/concepticon-data. The above way of accessing the API should be documented and illustrated with examples.

**Comment by xrotwang** [comment]
Importing from `__main__` seems a bit weird, I think. So if we want to allow access to a pylexibank configuration, the `configure` function should be exposed in `__init__`, i.e. `from pylexibank import configure` should be possible.

**Comment by LinguList** [comment]
Yes, I agree, I was feeling a bit weird, when I did this.

**Comment by chrzyki** [comment]
Yep, that would be good.

**Comment by chrzyki** [comment]
I consider this all good now with `cldfbench`, `catconfig` & co.
