### ISSUE TITLE
Accessing attributes takes unexpectedly long

### ISSUE THREAD

**Issue by d97hah** [glottolog/pyglottolog#7]
import pyglottolog.api
gl = pyglottolog.api.Glottolog("glottolog")
lgs = [l for l in gl.languoids()] # if l.level.value == 2]

#This takes pretty no time
xs = [None for l in lgs]

#This takes 10 min
xs = [l for l in lgs if type(l.family) == type(None)]

On my Python 2.7 (Windows). I get similar time consumption accessing other attributes from a series of languoid objects. Is this expected behavior?

**Comment by xrotwang** [comment]
Iterating over all languoids takes about 10 secs on my machine.

Accessing the family attribute is really expensive. If all you need is
glottocode or name of the family, go with Languoid.lineage[0]

d97hah <notifications@github.com> schrieb am Di., 14. Mai 2019, 21:35:

**Comment by xrotwang** [comment]
The problem with the `family` attribute is that it calls [`ancestors`](https://github.com/clld/pyglottolog/blob/6d0be4d9e568c89c0db327b9bbb51ed7f414cc5c/src/pyglottolog/languoids/languoid.py#L218-L228) - thus reads all languoids in its lineage from disk - again, in your case. So it's basically only useful if you are interested in a small number of languoids.

For operations on many (or all) languoids, one should stick with the methods that accept a `nodes` argument, like [`ancestors_from_nodemap`](https://github.com/clld/pyglottolog/blob/6d0be4d9e568c89c0db327b9bbb51ed7f414cc5c/src/pyglottolog/languoids/languoid.py#L213). The typical usage would look like this:
```python
glottolog = pyglottolog.api.Glottolog("glottolog")
nodes = {l.id: l for l in glottolog.languoids()}
xs = [l for l in nodes.values() if not l.ancestors_from_nodemap(nodes)]
```
but in this case you'd actually use
```python
xs = [l for l in nodes.values() if not l.lineage]
```

**Comment by xrotwang** [comment]
Will leave this open until documentation is updated. And I agree, it was a bad API design to have properties - i.e. essentially attributes - which do stuff like I/O on access. That kind of behaviour is only acceptable in methods, I'd say.

**Comment by d97hah** [comment]
Ok I understand!

Pada tanggal Rab, 15 Mei 2019 pukul 14.04 Robert Forkel <
notifications@github.com> menulis:
